{% set name = "gitea" %}
{% set version = "1.5.3" %}

package:
  name: gitea
  version: {{ version }}

source:
  fn: gitea-{{ version }}.tar.gz
  url: https://github.com/go-gitea/gitea/archive/v{{ version }}.tar.gz
  sha256: 3a94982d1fa0549e26e2c86f859bc09dda480a98a6b07ce5682257f3ce7de188
  folder: src/code.gitea.io/gitea

build:
  number: 0
  binary_relocation: False
  skip: True   # [win32]

requirements:
  build:
    - make
    - m2-make   # [win]
    - {{ compiler('go') }}
  run:
    - git

test:
  commands:
    - gitea --help

about:
  home: https://gitea.io
  license: MIT
  summary: Git with a cup of tea
  description: |
      The goal of this project is to make the easiest, fastest, and most
      painless way of setting up a self-hosted Git service.
  dev_url: https://github.com/go-gitea/gitea
  doc_url: https://docs.gitea.io

extra:
  recipe-maintainers:
    - nehaljwani
