travis:
  secure:
    BINSTAR_TOKEN: DtfUa4IS73l+OTrHPixLldkIE6BuhpmkfBvoaJ1HA71n5U0XpcdIf4NK62X7/HYcLkaKz0oO+aJrmg5XT3jJ192+evjmidp6FEuclqI5sFTkgsD9EwAeE28BKK4EaJbn+4waic1kwYb7XX0ZnTElRjx0wYKl2JTYdH7LjpxXH6abRi1/etshZs+0XodW+MBJx9Kw6zs91wzDlBjUJq3iOt8SLmsvBU7YY9hUTa3V6EENlJXFDYKI3LWwgx6KIp2MSZx49eVyDM+XZO2BeQ8Qv9sQwl6QKct/WmZpsaslCL92TwTaPg3j0T+6pzsFQkGl8NdT4JAeFSsfPGLWVCrzv4tiL5KNnrLbmkq0mK1WEqfcqgOxBvhkeLHHOgcAaySYGlV02bIRK69AlAGJZZHTQQMr9ikpUuH7ZYjbrsh9CRJcXfBccqTLmURXOIk1tO6JLLZihLNjUa0xM40MRby7XGuHedizQTfxQHMLnd3cmqs59gniuvq5yBT1dxsBeFinuFodrJGgZT+AiF3TTuV6VuhSibzkjPP3ohvTREwXoB2eRbrTx5nmn6djRGpJy48CpUtOn04AZjL1l51uVRSu2vbshmo3rcC5z1TpvaaM2MDxz2NjCx6VF9Cjw5up43ubwXjIh0dgcBvfaI433nDHoSBr0Ip/O7bHS4I76iD3xGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
